#!/bin/bash
set -euo pipefail

SCRIPT_PATH="$0"
SCRIPT_DIR=$(dirname ${SCRIPT_PATH})
. "${SCRIPT_DIR}/../khakis/bin/common.sh"

ZOOKEEPER_IMAGE=${ZOOKEEPER_IMAGE:-"eyeris/zookeeper"}

ZOOKEEPER_CPUSHARES=${ZOOKEEPER_CPUSHARES:-4}
ZOOKEEPER_MEMORY=${ZOOKEEPER_MEMORY:-512m}

# Container configuration
EYERIS_PLATFORM_DIRECT_PORTS=${EYERIS_PLATFORM_DIRECT_PORTS:-1}
EYERIS_PLATFORM_PORTS=${EYERIS_PLATFORM_PORTS:--P}
EYERIS_DEVELOPER_MODE=${EYERIS_DEVELOPER_MODE:-true}

ZOOKEEPER_CMD="--name=eyeris-zookeeper --cpu-shares=$ZOOKEEPER_CPUSHARES --memory=$ZOOKEEPER_MEMORY $ZOOKEEPER_IMAGE"

if [ -n "${EYERIS_PLATFORM_DIRECT_PORTS}" ] && [ "${EYERIS_PLATFORM_PORTS}" == "-P" ]; then
    ZOOKEEPER_CMD="-P -p 2181:2181 -p 2888:2888 -p 3888:3888 $ZOOKEEPER_CMD"
fi

docker_run -d $ZOOKEEPER_CMD

sleep 2
wait

