/*
 * Copyright 2019 Arcus Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// project specific build settings, dependencies, etc.
plugins {
    id 'java'
    id 'org.unbroken-dome.xjc'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

ext {
    generatedSrcDir = file('src/generated/java')
    xsdDir = file('common/arcus-protocol/build/schema')
    episodeDir = layout.buildDirectory.dir('common/arcus-protocol/build/schema')
}

dependencies {
    runtimeOnly 'org.glassfish.jaxb:jaxb-runtime:4.0.0'
    compileOnly 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.0'
    
    implementation libraries.commons_lang
    implementation libraries.handlebars
    implementation libraries.jcommander
}

sourceSets {
    main {
        java {
            srcDir generatedSrcDir
        }
    }
}

xjc {
    ipcd {
        schema          = fileTree(dir: xsdDir, include: '*.xsd')
        outputDirectory = generatedSrcDir
        generatePackage = 'com.iris.protocol.ipcd.xml.model'
        generateEpisode = true
        episodeFile     = episodeDir.map {
            it.file('urn-com-iris-protocol-ipcd-xml-model.episode').asFile
        }.get()
    }

    ipcdAos {
        schema          = fileTree(dir: xsdDir, include: '*-aos.xsd')
        outputDirectory = generatedSrcDir
        generatePackage = 'com.iris.protocol.ipcd.aos.xml.model'
        generateEpisode = true
        episodeFile     = episodeDir.map {
            it.file('urn-com-iris-protocol-ipcd-aos-xml-model.episode').asFile
        }.get()
    }
}

task cleanGeneratedSource(type: Delete) {
    delete generatedSrcDir
}

clean.dependsOn cleanGeneratedSource

compileJava.dependsOn xjc
compileTestJava.dependsOn xjc
eclipseClasspath.dependsOn xjc

